-- AULA 5 - EXERCICIO

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;

-- EX 1

SELECT 
    FIRST_NAME,
    HIRE_DATE
        FROM EMPLOYEES;

-- EX 2

SELECT
    FIRST_NAME,
    SALARY,
    SALARY * 1.05 AS "AUMENTO DE 5%",
    SALARY * 1.08 AS "AUMENTO DE 8%"
        FROM EMPLOYEES;

-- EX 3

SELECT * FROM COUNTRIES;

SELECT
    COUNTRY_NAME
        FROM COUNTRIES
        WHERE COUNTRY_NAME LIKE '%I%' OR COUNTRY_NAME LIKE '%i%';
    
-- PARTE 2 - SELECAO COM CODICOES
-- EX 1

SELECT
    FIRST_NAME,
    LAST_NAME
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID = 90;
        
SELECT
    FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME
        FROM EMPLOYEES
        WHERE DEPARTMENT_ID = 90;

-- EX 2

SELECT * FROM JOBS;

SELECT *
    FROM JOBS
    WHERE MAX_SALARY BETWEEN 5000 AND 10000;
        
-- EX 3

SELECT *
    FROM EMPLOYEES
    WHERE SALARY >= 4000;
    
-- EX4

SELECT
    FIRST_NAME,
    EXTRACT (YEAR FROM HIRE_DATE) 
        FROM EMPLOYEES
        WHERE EXTRACT(YEAR FROM HIRE_DATE) >= 1995;
        
-- DISTINCT

SELECT DISTINCT
    DEPARTMENT_ID
        FROM EMPLOYEES
            ORDER BY DEPARTMENT_ID;
            
SELECT DISTINCT
    DEPARTMENT_ID
        FROM EMPLOYEES
            ORDER BY 1;
            
-- TO_CHAR E TO_DATE

SELECT
    FIRST_NAME,
    HIRE_DATE
        FROM EMPLOYEES
        WHERE TO_CHAR(HIRE_DATE, 'YYYY') = 1995;
        
SELECT
    FIRST_NAME,
    HIRE_DATE
        FROM EMPLOYEES
        WHERE TO_DATE(HIRE_DATE, 'DD-MM-YYYY') BETWEEN '01-01-1995' AND '31-12-1999' 
        ORDER BY 2;
    
ALTER SESSION
    SET NLS_DATE_FORMAT = 'DD/MM/YYYY';

ALTER SESSION
    SET NLS_DATE_LANGUAGE = 'PORTUGUESE';



